name: Main

on: [push]

env:
  APP_NAME: ${{APP_NAME}}
  RUNTIME_PLATFORM: ${{RUNTIME_PLATFORM}}
  GCP_PROJECT_ID: ${{GCP_PROJECT_ID}}

jobs:
  # Build the cli and test project setup
  backpack_build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.8
      - uses: actions/checkout@v1
      - run: .backpack/github/build-backpack.sh

  # Build and test frontend JS and CSS assets
  frontend_build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn run build
      - uses: actions/upload-artifact@v1
        with:
          name: frontend-assets
          path: build

  # Build and test backend python
  server_build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

  # Build and publish docker artifact
  release_build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/disabled'
    needs: frontend_build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: frontend-assets
          path: build
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - run: .backpack/github/build-release.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
