name: Deployment

on: [push]

env:
  APP_NAME: backpack-example
  RUNTIME_PLATFORM: CLOUD_RUN
  GCP_PROJECT_ID: default-263000

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.8
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # Run terraform plan
      - run: .backpack/github/install-terraform.sh
      - run: .backpack/github/terraform-plan.sh
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - run: .backpack/github/terraform-apply.sh
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Setup secret variables
      - run: .backpack/github/install-berglas.sh
      - run: |
          mkdir -p var/env
          ./backpack vars get > /dev/null 2>&1
          ./backpack vars get > var/env/production.json

      # Run deployment script
      # - run: .backpack/github/deploy.sh
      #   env:
      #     DIGITALOCEAN_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}

      # Run ansible on server
      - run: .backpack/github/setup-ansible.sh
        env: 
          DIGITALOCEAN_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
      - run: |
          ansible-playbook .backpack/digitalocean/playbooks/post-deploy.yml \
            --inventory ./etc/ansible/hosts \
            --user root
