name: Infrastructure

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p .backpack/etc/ssh
      - run: mkdir -p .backpack/etc/ansible
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan -H 198.199.83.49 >> ~/.ssh/known_hosts
      - run: echo "198.199.83.49" > .backpack/etc/ansible/hosts
      - run: echo "${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}" > ~/.ssh/id_rsa && sudo chmod 600 ~/.ssh/id_rsa
      - run: ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub && sudo chmod 600 ~/.ssh/id_rsa.pub
      - run: sudo apt-add-repository ppa:ansible/ansible && sudo apt update && sudo apt install ansible
      - run: |
          ansible-playbook .backpack/digitalocean/bootstrap/playbook.yml \
            -i .backpack/etc/ansible/hosts \
            -u root
