name: Infrastructure

on: [workflow_dispatch]

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - uses: ./.backpack/github/actions/set-env

      # Run terraform
      - run: .backpack/github/install-terraform.sh
      - run: .backpack/github/terraform-plan.sh
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - run: .backpack/github/terraform-apply.sh
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Run ansible on server
      - run: .backpack/github/setup-ansible.sh
        env: 
          DIGITALOCEAN_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
      - run: |
          ansible-playbook .backpack/digitalocean/playbooks/setup.yml \
            --inventory ./etc/ansible/hosts \
            --user root
