name: Infrastructure

on: [workflow_dispatch]

jobs:
  # Build the cli and test project setup
  backpack_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo Hello!
