name: Main

on: [push]

jobs:
  build_backpack:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.8
      - uses: actions/checkout@v1
      - uses: ./.backpack/delivery/actions/app-context-action
      # - run: .backpack/delivery/actions/test-backpack.sh

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - run: yarn run build
      - uses: actions/upload-artifact@v1
        with:
          name: frontend-artifact
          path: build

  build_server:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - uses: ./.backpack/delivery/actions/app-context-action
      - run: docker-compose build
      - run: docker-compose run "$BACKPACK_DOCKER_SERVICE_NAME" .backpack/delivery/actions/test-server.sh

  release:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: build_frontend
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: frontend-artifact
          path: build
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - run: .backpack/delivery/actions/install-berglas.sh
      - run: .backpack/delivery/actions/install-terraform.sh
      - uses: ./.backpack/delivery/actions/app-context-action
      - run: .backpack/delivery/actions/build-release.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
